//! Mechanical generation of the Electron shim protocol module from the Rust-owned descriptor.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};
use sha2::{Digest as _, Sha256};

pub(crate) const DESCRIPTOR_RELPATH: &str = "crates/openbot-contracts/engine-protocol-v4.json";
pub(crate) const MODULE_RELPATH: &str = "crates/openbot-desktop/engine-shim/generated/protocol.mjs";
pub(crate) const HASH_RELPATH: &str = "crates/openbot-contracts/generated/engine-protocol.sha256";

pub(crate) fn generate(root: &Path, check: bool) -> Result<()> {
    let rendered = render(root)?;
    let hash = format!("{:x}\n", Sha256::digest(rendered.as_bytes()));
    if check {
        check_bytes(root, MODULE_RELPATH, rendered.as_bytes())?;
        check_bytes(root, HASH_RELPATH, hash.as_bytes())?;
        println!(
            "engine protocol --check: ok (version={}; sha256={})",
            descriptor(root)?["version"],
            hash.trim()
        );
        return Ok(());
    }
    atomic_write(root.join(MODULE_RELPATH), rendered.as_bytes())?;
    atomic_write(root.join(HASH_RELPATH), hash.as_bytes())?;
    println!(
        "engine protocol: generated {MODULE_RELPATH} and {HASH_RELPATH} (sha256={})",
        hash.trim()
    );
    Ok(())
}

pub(crate) fn render(root: &Path) -> Result<String> {
    let descriptor = descriptor(root)?;
    validate_descriptor(&descriptor)?;
    let compact = serde_json::to_string(&descriptor).context("serialize engine protocol")?;
    Ok(format!(
        "// Generated by `cargo xtask engine protocol`; do not hand edit.\n\
         export const PROTOCOL = Object.freeze({compact});\n\
         export const PROTOCOL_VERSION = PROTOCOL.version;\n\
         export const RELEASE_EPOCH = PROTOCOL.release_epoch;\n\
         export const MAX_BOOT_BYTES = PROTOCOL.max_boot_bytes;\n\
         export const MAX_CONTROL_FRAME_BYTES = PROTOCOL.max_control_frame_bytes;\n\
         export const MAX_IMAGE_BYTES = PROTOCOL.max_image_bytes;\n\
         export const FRAME_MAGIC = PROTOCOL.frame_magic;\n\
         export const FRAME_HELLO_MAGIC = PROTOCOL.frame_hello_magic;\n\
         export const FRAME_FIXED_HEADER_BYTES = PROTOCOL.frame_fixed_header_bytes;\n"
    ))
}

fn descriptor(root: &Path) -> Result<serde_json::Value> {
    let path = root.join(DESCRIPTOR_RELPATH);
    serde_json::from_str(
        &fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?,
    )
    .context("parse engine protocol descriptor")
}

fn validate_descriptor(value: &serde_json::Value) -> Result<()> {
    let object = value
        .as_object()
        .ok_or_else(|| anyhow!("engine protocol descriptor must be an object"))?;
    let expected = [
        "commands",
        "events",
        "frame_fixed_header_bytes",
        "frame_hello_magic",
        "frame_magic",
        "image_formats",
        "input_kinds",
        "max_boot_bytes",
        "max_control_frame_bytes",
        "max_image_bytes",
        "release_epoch",
        "roles",
        "schema",
        "screencast",
        "version",
    ]
    .into_iter()
    .collect::<std::collections::BTreeSet<_>>();
    let actual = object
        .keys()
        .map(String::as_str)
        .collect::<std::collections::BTreeSet<_>>();
    if actual != expected {
        bail!("engine protocol keys drift: expected {expected:?}, got {actual:?}");
    }
    if value["schema"] != "openbot-engine-protocol"
        || value["version"] != 4
        || value["release_epoch"] != 5
        || value["frame_magic"] != "OBFRAME2"
        || value["frame_hello_magic"] != "OBFHELLO"
        || value["frame_fixed_header_bytes"] != 76
    {
        bail!("engine protocol fixed v4 values drift");
    }
    for (key, expected) in [
        (
            "roles",
            ["browser_computer", "sandboxed_component"].as_slice(),
        ),
        (
            "commands",
            [
                "start",
                "input",
                "frame_ack",
                "screencast",
                "stop",
                "shutdown",
            ]
            .as_slice(),
        ),
        (
            "events",
            [
                "hello",
                "ready",
                "started",
                "input_applied",
                "screencast_state",
                "stopped",
                "shutdown_complete",
                "error",
            ]
            .as_slice(),
        ),
        (
            "input_kinds",
            [
                "mouse_move",
                "mouse_down",
                "mouse_up",
                "wheel",
                "key_down",
                "raw_key_down",
                "key_up",
                "insert_text",
            ]
            .as_slice(),
        ),
        ("image_formats", ["jpeg"].as_slice()),
    ] {
        let got = value[key]
            .as_array()
            .ok_or_else(|| anyhow!("engine protocol `{key}` must be an array"))?
            .iter()
            .map(|entry| {
                entry
                    .as_str()
                    .ok_or_else(|| anyhow!("engine protocol `{key}` contains non-string"))
            })
            .collect::<Result<Vec<_>>>()?;
        if got != expected {
            bail!("engine protocol `{key}` drift: expected {expected:?}, got {got:?}");
        }
    }
    let screencast = value["screencast"]
        .as_object()
        .ok_or_else(|| anyhow!("engine protocol `screencast` must be an object"))?;
    let expected_screencast = serde_json::json!({
        "format": "jpeg",
        "quality": 70,
        "max_width": 1280,
        "max_height": 800,
        "every_nth_frame": 1,
        "max_frames_in_flight": 1,
        "send_last_frame": true,
    });
    if screencast != expected_screencast.as_object().expect("object literal") {
        bail!("engine protocol screencast settings drift");
    }
    Ok(())
}

fn check_bytes(root: &Path, relative: &str, expected: &[u8]) -> Result<()> {
    let path = root.join(relative);
    let actual =
        fs::read(&path).with_context(|| format!("read {relative}; run protocol generator"))?;
    if actual != expected {
        bail!("{relative} is stale; run `cargo xtask engine protocol`");
    }
    Ok(())
}

fn atomic_write(path: PathBuf, bytes: &[u8]) -> Result<()> {
    let parent = path
        .parent()
        .ok_or_else(|| anyhow!("generated path has no parent"))?;
    fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    let temporary = path.with_extension("tmp");
    fs::write(&temporary, bytes).with_context(|| format!("write {}", temporary.display()))?;
    if path.exists() {
        fs::remove_file(&path).with_context(|| format!("replace {}", path.display()))?;
    }
    fs::rename(&temporary, &path).with_context(|| format!("publish {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::validate_descriptor;

    #[test]
    fn descriptor_domain_is_closed() {
        let value: serde_json::Value = serde_json::from_str(include_str!(
            "../../../../crates/openbot-contracts/engine-protocol-v4.json"
        ))
        .expect("descriptor");
        validate_descriptor(&value).expect("closed descriptor");
        let mut changed = value;
        let mut stale = changed.clone();
        stale["version"] = serde_json::json!(2);
        stale["release_epoch"] = serde_json::json!(2);
        assert!(validate_descriptor(&stale).is_err());
        changed["commands"] = serde_json::json!(["start", "free_method"]);
        assert!(validate_descriptor(&changed).is_err());
    }
}
