//! Post-build external WASM bootstrap for strict-CSP Trunk output.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};

const BOOTSTRAP_NAME: &str = "openbot-bootstrap.mjs";

pub(crate) fn run() -> Result<()> {
    let staging = std::env::var_os("TRUNK_STAGING_DIR")
        .map(PathBuf::from)
        .ok_or_else(|| {
            anyhow!("TRUNK_STAGING_DIR is required; ui-finalize only runs as a Trunk hook")
        })?;
    if !staging.is_dir() {
        bail!(
            "Trunk staging directory does not exist: {}",
            staging.display()
        );
    }
    let (javascript, wasm) = find_bindgen_pair(&staging)?;
    let bootstrap = render_bootstrap(&javascript, &wasm)?;
    fs::write(staging.join(BOOTSTRAP_NAME), bootstrap)?;
    println!("ui-finalize: wrote external strict-CSP bootstrap {BOOTSTRAP_NAME}");
    Ok(())
}

fn find_bindgen_pair(staging: &Path) -> Result<(String, String)> {
    let mut javascript = Vec::new();
    let mut wasm = Vec::new();
    for entry in fs::read_dir(staging).with_context(|| format!("read {}", staging.display()))? {
        let entry = entry?;
        if !entry.file_type()?.is_file() {
            continue;
        }
        let name = entry
            .file_name()
            .into_string()
            .map_err(|_| anyhow!("non-UTF8 Trunk artifact name"))?;
        if name.ends_with(".js") {
            javascript.push(name);
        } else if name.ends_with("_bg.wasm") {
            wasm.push(name);
        }
    }
    javascript.sort();
    wasm.sort();
    match (javascript.as_slice(), wasm.as_slice()) {
        ([javascript], [wasm]) => Ok((javascript.clone(), wasm.clone())),
        _ => bail!(
            "expected one wasm-bindgen JS/WASM pair, got javascript={javascript:?}, wasm={wasm:?}"
        ),
    }
}

fn render_bootstrap(javascript: &str, wasm: &str) -> Result<String> {
    for name in [javascript, wasm] {
        if name.is_empty()
            || !name
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_' | b'.'))
        {
            bail!("unsafe Trunk artifact name `{name}`");
        }
    }
    Ok(format!(
        "// @generated by cargo xtask ui-finalize; no business logic.\n\
         import init from \"./{javascript}\";\n\
         const wasm = await init({{ module_or_path: \"/{wasm}\" }});\n\
         dispatchEvent(new CustomEvent(\"TrunkApplicationStarted\", {{ detail: {{ wasm }} }}));\n"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bootstrap_uses_module_relative_js_and_root_absolute_wasm_for_nested_routes() {
        let value =
            render_bootstrap("openbot-ui-deadbeef.js", "openbot-ui-deadbeef_bg.wasm").unwrap();
        assert!(value.contains("import init from \"./openbot-ui-deadbeef.js\""));
        assert!(value.contains("module_or_path: \"/openbot-ui-deadbeef_bg.wasm\""));
        assert!(!value.contains("module_or_path: \"./"));
        assert!(!value.contains("http:"));
        assert!(!value.contains("https:"));
        assert!(render_bootstrap("../escape.js", "ok_bg.wasm").is_err());
    }
}
